# Generated by Django 5.0 on 2026-02-15 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Bot nomi')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='Username')),
                ('bot_id', models.BigIntegerField(unique=True, verbose_name='Bot ID')),
                ('encrypted_token', models.TextField(verbose_name='Shifrlangan token')),
                ('webhook_secret', models.CharField(blank=True, max_length=255, verbose_name='Webhook secret')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('welcome_message', models.TextField(blank=True, verbose_name='Xush kelibsiz xabari')),
                ('auto_reply_enabled', models.BooleanField(default=False, verbose_name='Auto reply yoqilgan')),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('error', 'Error')], default='active', max_length=20, verbose_name='Status')),
                ('total_users', models.IntegerField(default=0, verbose_name='Foydalanuvchilar soni')),
                ('total_messages', models.IntegerField(default=0, verbose_name='Xabarlar soni')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('last_active', models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi faollik')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bots', to=settings.AUTH_USER_MODEL, verbose_name='Egasi')),
            ],
            options={
                'verbose_name': 'Bot',
                'verbose_name_plural': 'Botlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutoReplyRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.TextField(verbose_name="Kalit so'zlar (vergul bilan)")),
                ('reply_text', models.TextField(verbose_name='Javob matni')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('priority', models.IntegerField(default=0, verbose_name='Prioritet')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_replies', to='bots.bot', verbose_name='Bot')),
            ],
            options={
                'verbose_name': 'Auto Reply',
                'verbose_name_plural': 'Auto Replies',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='Savol')),
                ('answer', models.TextField(verbose_name='Javob')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('order', models.IntegerField(default=0, verbose_name='Tartib')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='bots.bot', verbose_name='Bot')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
