# Generated by Django 5.0 on 2026-02-15 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Sana')),
                ('messages_sent', models.IntegerField(default=0, verbose_name='Yuborilgan xabarlar')),
                ('messages_received', models.IntegerField(default=0, verbose_name='Qabul qilingan xabarlar')),
                ('new_users', models.IntegerField(default=0, verbose_name='Yangi foydalanuvchilar')),
                ('active_users', models.IntegerField(default=0, verbose_name='Faol foydalanuvchilar')),
                ('avg_response_time', models.FloatField(default=0.0, verbose_name="O'rtacha javob vaqti (sekund)")),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='bots.bot', verbose_name='Bot')),
            ],
            options={
                'verbose_name': 'Kunlik statistika',
                'verbose_name_plural': 'Kunlik statistikalar',
                'ordering': ['-date'],
                'unique_together': {('bot', 'date')},
            },
        ),
    ]
