# Generated by Django 5.0 on 2026-02-15 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_message_id', models.BigIntegerField(verbose_name='Telegram Message ID')),
                ('sender', models.CharField(choices=[('user', 'User'), ('bot', 'Bot')], max_length=10, verbose_name='Yuboruvchi')),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('photo', 'Photo'), ('video', 'Video'), ('audio', 'Audio'), ('voice', 'Voice'), ('document', 'Document'), ('sticker', 'Sticker'), ('location', 'Location'), ('contact', 'Contact')], default='text', max_length=20, verbose_name='Xabar turi')),
                ('text', models.TextField(blank=True, verbose_name='Matn')),
                ('file_id', models.CharField(blank=True, max_length=255, verbose_name='File ID')),
                ('file_path', models.CharField(blank=True, max_length=500, verbose_name='File path')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='File hajmi')),
                ('is_forwarded', models.BooleanField(default=False, verbose_name='Forward qilingan')),
                ('is_read', models.BooleanField(default=False, verbose_name="O'qilgan")),
                ('is_deleted', models.BooleanField(default=False, verbose_name="O'chirilgan")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chats.chat', verbose_name='Chat')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='bot_messages.message', verbose_name='Javob')),
            ],
            options={
                'verbose_name': 'Xabar',
                'verbose_name_plural': 'Xabarlar',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['chat', 'created_at'], name='bot_message_chat_id_bba185_idx'), models.Index(fields=['telegram_message_id'], name='bot_message_telegra_e8955b_idx')],
            },
        ),
    ]
