# Generated by Django 5.0 on 2026-02-16 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_messages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='file_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='File ID'),
        ),
        migrations.AlterField(
            model_name='message',
            name='file_path',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='File path'),
        ),
    ]
